default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: minidoc_development
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: minidoc_test
  username: root
  password:
  host: localhost

preview:
  <<: *default
  database: minidoc_preview
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: minidoc_production
  url: <%= ENV['DATABASE_URL'] %>
