default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: minidoc_development

test:
  <<: *default
  database: minidoc_test

preview:
  <<: *default
  database: minidoc_preview
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: mysql

production:
  <<: *default
  database: minidoc_production
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  username: <%= ENV['MINIDOC_DATABASE_USER']%>
  password: <%= ENV['MINIDOC_DATABASE_PASSWORD'] %>
