default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: minidoc_development

test:
  <<: *default
  database: minidoc_test

production:
  <<: *default
  database: minidoc_production
  username: <%= ENV['MINIDOC_DATABASE_USER']%>
  password: <%= ENV['MINIDOC_DATABASE_PASSWORD'] %>
  host:     <%= ENV['MINIDOC_DATABASE_HOST'] %>

preview:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/preview.sqlite3
